# Configuração para implantação do Streamlit
[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#EFF6FF"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50
address = "0.0.0.0"
port = 8501
headless = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
