
[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#EFF6FF"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50
